---
title: "GoogleVis"
author: "Sam Eckhardt"
date: "Tuesday, November 04, 2014"
output: html_document
---
## Welcome to this simple html page with two google visualizations. 

Hello, this should be fun. 

```{r setOptions, message=FALSE,echo=FALSE}
library(googleVis)
#op <- options(gvis.plot.tag='chart')
```


## Histogram

```{r results='asis'}
set.seed(123)
datHist=data.frame(A=rpois(100, 20),
                   B=rpois(100, 5),
                   C=rpois(100, 50))

Hist <- gvisHistogram(datHist, options=list(
  legend="{ position: 'top', maxLines: 2 }",
  colors="['#5C3292', '#1A8763', '#871B47']",
  width=750, height=360))
plot(Hist)
print(Hist,file="hist.html")
```
Histogram, much wow. 

<iframe src="hist.html" width="800" height="600"></iframe>

## Line Chart

```{r results='asis'}
df=data.frame(country=c("US", "GB", "BR"), 
              val1=c(10,13,14), 
              val2=c(23,12,32))
Line <- gvisLineChart(df,options=list(width=750, height=500))
plot(Line)
print(Line,file="line.html")
```
<iframe src="line.html" width="800" height="600"></iframe>
